# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard(object):
    def setupUi(self, dashboard):
        dashboard.setObjectName("dashboard")
        dashboard.resize(1200, 850)
        self.centralwidget = QtWidgets.QWidget(dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.312, y1:1, x2:0.321782, y2:0, stop:0.164179 rgba(231, 206, 161, 251), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 30, 1250, 750))
        self.label.setStyleSheet("QLabel {\n"
"   background-color:transparent;\n"
"\n"
"}\n"
"")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/o_logo.png"))
        self.label.setScaledContents(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 1161, 791))
        self.widget_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 80));\n"
"border-radius:15px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setMinimumSize(QtCore.QSize(0, 250))
        self.frame.setStyleSheet("background-color:transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dashboard_label = QtWidgets.QLabel(self.frame)
        self.dashboard_label.setGeometry(QtCore.QRect(320, 80, 541, 141))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dashboard_label.setFont(font)
        self.dashboard_label.setStyleSheet("background-color: transparent;\n"
"font-size: 72px;\n"
"color: black;\n"
"font: \"Gulzar\";\n"
"")
        self.dashboard_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dashboard_label.setObjectName("dashboard_label")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color:transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.Inventory_DB = QtWidgets.QToolButton(self.frame_2)
        self.Inventory_DB.setGeometry(QtCore.QRect(80, 110, 200, 130))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Inventory_DB.setFont(font)
        self.Inventory_DB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Inventory_DB.setStyleSheet("QToolButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 15px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"padding:10px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"background-color: rgba(244,237,228,200);\n"
"border-radius: 20px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/inventory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/inventory-w.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/inventory.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.Inventory_DB.setIcon(icon)
        self.Inventory_DB.setIconSize(QtCore.QSize(100, 100))
        self.Inventory_DB.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.Inventory_DB.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Inventory_DB.setAutoRaise(False)
        self.Inventory_DB.setObjectName("Inventory_DB")
        self.Order_DB = QtWidgets.QToolButton(self.frame_2)
        self.Order_DB.setGeometry(QtCore.QRect(350, 110, 200, 130))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Order_DB.setFont(font)
        self.Order_DB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Order_DB.setStyleSheet("QToolButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 15px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"padding:10px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"background-color: rgba(244,237,228,200);\n"
"border-radius: 20px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-order-management-64 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Order_DB.setIcon(icon1)
        self.Order_DB.setIconSize(QtCore.QSize(100, 100))
        self.Order_DB.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Order_DB.setObjectName("Order_DB")
        self.Report_DB = QtWidgets.QToolButton(self.frame_2)
        self.Report_DB.setGeometry(QtCore.QRect(610, 110, 200, 130))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Report_DB.setFont(font)
        self.Report_DB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Report_DB.setStyleSheet("QToolButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 15px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"padding:10px;\n"
"\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"background-color: rgba(244,237,228,200);\n"
"border-radius: 20px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-health-graph-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Report_DB.setIcon(icon2)
        self.Report_DB.setIconSize(QtCore.QSize(100, 100))
        self.Report_DB.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Report_DB.setObjectName("Report_DB")
        self.Supplier_DB = QtWidgets.QToolButton(self.frame_2)
        self.Supplier_DB.setGeometry(QtCore.QRect(860, 110, 200, 130))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Supplier_DB.setFont(font)
        self.Supplier_DB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Supplier_DB.setStyleSheet("QToolButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 15px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"padding:10px;\n"
"\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"background-color: rgba(244,237,228,200);\n"
"border-radius: 20px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/supplier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Supplier_DB.setIcon(icon3)
        self.Supplier_DB.setIconSize(QtCore.QSize(100, 100))
        self.Supplier_DB.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Supplier_DB.setObjectName("Supplier_DB")
        self.Logout_DB = QtWidgets.QToolButton(self.frame_2)
        self.Logout_DB.setGeometry(QtCore.QRect(1020, 430, 70, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Logout_DB.setFont(font)
        self.Logout_DB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Logout_DB.setStyleSheet("QToolButton {\n"
"    background-color: transparent;\n"
"    border-radius: 50px; \n"
"   \n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgba(244, 237, 228, 200);\n"
"    border-radius: 50px; \n"
"}\n"
"")
        self.Logout_DB.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/LOGOUT BUTTON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Logout_DB.setIcon(icon4)
        self.Logout_DB.setIconSize(QtCore.QSize(100, 100))
        self.Logout_DB.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Logout_DB.setObjectName("Logout_DB")
        self.verticalLayout.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        dashboard.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(dashboard)
        self.statusbar.setObjectName("statusbar")
        dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(dashboard)
        QtCore.QMetaObject.connectSlotsByName(dashboard)

    def retranslateUi(self, dashboard):
        _translate = QtCore.QCoreApplication.translate
        dashboard.setWindowTitle(_translate("dashboard", "MainWindow"))
        self.dashboard_label.setText(_translate("dashboard", "DASHBOARD"))
        self.Inventory_DB.setText(_translate("dashboard", "Inventory Management"))
        self.Order_DB.setText(_translate("dashboard", "Order Management"))
        self.Report_DB.setText(_translate("dashboard", "Report Management"))
        self.Supplier_DB.setText(_translate("dashboard", "Supplier Management"))
import resources_rc
