# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
         # Hide the maximize button (set window flags)
        MainWindow.setWindowFlags(MainWindow.windowFlags() & ~QtCore.Qt.WindowMaximizeButtonHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.312, y1:1, x2:0.321782, y2:0, stop:0.164179 rgba(231, 206, 161, 251), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.logo = QtWidgets.QLabel(self.widget_2)
        self.logo.setGeometry(QtCore.QRect(30, 120, 550, 550))
        self.logo.setStyleSheet("background-color:transparent;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/newPrefix/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(20, 100, 540, 590))
        self.widget_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 80));\n"
"border-radius:20px;")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 180))
        self.widget_5.setStyleSheet("background-color:transparent;")
        self.widget_5.setObjectName("widget_5")
        self.stock_label = QtWidgets.QLabel(self.widget_5)
        self.stock_label.setGeometry(QtCore.QRect(30, 20, 471, 141))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading Semibold")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stock_label.setFont(font)
        self.stock_label.setStyleSheet("background-color: transparent;\n"
"font-size: 42px;\n"
"color: #FFF0F0;\n"
"font: \"Gulzar\";\n"
"")
        self.stock_label.setAlignment(QtCore.Qt.AlignCenter)
        self.stock_label.setObjectName("stock_label")
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setStyleSheet("BACKGROUND-COLOR:TRANSPARENT;")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_8 = QtWidgets.QWidget(self.widget_6)
        self.widget_8.setStyleSheet(" border-top: 2px solid white;   /* Top color */\n"
"  border-bottom: 2px solid white; /* Bottom color */\n"
"background-color:transparent;")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_10 = QtWidgets.QWidget(self.widget_8)
        self.widget_10.setStyleSheet("background-color:transparent;\n"
"border-top:0px;\n"
"border-bottom:0px;")
        self.widget_10.setObjectName("widget_10")
        self.unamae_lane = QtWidgets.QLabel(self.widget_10)
        self.unamae_lane.setGeometry(QtCore.QRect(40, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.unamae_lane.setFont(font)
        self.unamae_lane.setStyleSheet("background-color: transparent;\n"
"font-size: 20px;\n"
"color: #FFF9F9;\n"
"font-weight:bold;")
        self.unamae_lane.setAlignment(QtCore.Qt.AlignCenter)
        self.unamae_lane.setObjectName("unamae_lane")
        self.username = QtWidgets.QLineEdit(self.widget_10)
        self.username.setGeometry(QtCore.QRect(200, 40, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username.setFont(font)
        self.username.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.username.setStyleSheet("background-color:#ECE1C5;\n"
"border-radius:10px;\n"
"padding-left:40px;")
        self.username.setText("")
        self.username.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.username.setPlaceholderText("")
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.user_icon = QtWidgets.QLabel(self.widget_10)
        self.user_icon.setGeometry(QtCore.QRect(210, 50, 20, 25))
        self.user_icon.setText("")
        self.user_icon.setPixmap(QtGui.QPixmap(":/newPrefix/user-solid 1.png"))
        self.user_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.user_icon.setObjectName("user_icon")
        self.verticalLayout_3.addWidget(self.widget_10)
        self.widget_9 = QtWidgets.QWidget(self.widget_8)
        self.widget_9.setStyleSheet("background-color:transparent;\n"
"border-top:0px;\n"
"border-bottom:0px;")
        self.widget_9.setObjectName("widget_9")
        self.pass_label = QtWidgets.QLabel(self.widget_9)
        self.pass_label.setGeometry(QtCore.QRect(60, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pass_label.setFont(font)
        self.pass_label.setStyleSheet("background-color: transparent;\n"
"font-size: 20px;\n"
"color: #FFF9F9;\n"
"font-weight: bold;\n"
"")
        self.pass_label.setObjectName("pass_label")
        self.password = QtWidgets.QLineEdit(self.widget_9)
        self.password.setGeometry(QtCore.QRect(200, 30, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:#ECE1C5;\n"
"border-radius:10px;\n"
"padding-left: 40px;")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setCursorPosition(0)
        self.password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.password.setPlaceholderText("")
        self.password.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.pass_icon = QtWidgets.QLabel(self.widget_9)
        self.pass_icon.setGeometry(QtCore.QRect(210, 45, 21, 16))
        self.pass_icon.setStyleSheet("image: url(:/newPrefix/lock.png);")
        self.pass_icon.setText("")
        self.pass_icon.setObjectName("pass_icon")
        self.verticalLayout_3.addWidget(self.widget_9)
        self.widget_11 = QtWidgets.QWidget(self.widget_8)
        self.widget_11.setStyleSheet("background-color:transparent;\n"
"border-top:0px;\n"
"border-bottom:0px;")
        self.widget_11.setObjectName("widget_11")
        self.login = QtWidgets.QPushButton(self.widget_11)
        self.login.setGeometry(QtCore.QRect(170, 30, 150, 41))
        self.login.setStyleSheet("QPushButton {\n"
"     background-color: #ECE1C5;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"    color: black;\n"
"    font: \"Jost\";\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);  /* Light shadow for normal state */\n"
"    transition: background-color 0.3s, color 0.3s, box-shadow 0.3s, transform 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(244,237,228,200);\n"
"    color: rgb(255, 253, 253);\n"
"    border-radius: 10px;\n"
"    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.25);  /* Stronger shadow on hover */\n"
"    transform: scale(1.05);  /* Slightly enlarges the button */\n"
"}\n"
"")
        self.login.setObjectName("login")
        self.verticalLayout_3.addWidget(self.widget_11)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 90))
        self.widget_7.setStyleSheet("BACKGROUND-COLOR:TRANSPARENT;")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout.addWidget(self.widget_7)
        self.horizontalLayout.addWidget(self.widget_3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stock_label.setText(_translate("MainWindow", "STOCK MANAGEMENT \n"
"SYSTEM"))
        self.unamae_lane.setText(_translate("MainWindow", "USERNAME:"))
        self.pass_label.setText(_translate("MainWindow", "PASSWORD:"))
        self.login.setText(_translate("MainWindow", "LOGIN"))
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
