# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SC.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize
from PyQt5 import Qt, QtCore
import sys


class Ui_Sugarcafe(object):
    def setupUi(self, Sugarcafe):
        Sugarcafe.setObjectName("Sugarcafe")
        Sugarcafe.resize(1200, 850)
         # Hide the maximize and close buttons
        flags = Sugarcafe.windowFlags()  # Get the current window flags
        flags &= ~QtCore.Qt.WindowMaximizeButtonHint  # Disable the maximize button
        flags &= ~QtCore.Qt.WindowCloseButtonHint     # Disable the close button
        Sugarcafe.setWindowFlags(flags)  # Apply the updated flags
        self.centralwidget = QtWidgets.QWidget(Sugarcafe)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, 10, 1191, 821))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.312, y1:1, x2:0.321782, y2:0, stop:0.164179 rgba(231, 206, 161, 251), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(340, 30, 700, 700))
        self.label.setStyleSheet("background-color:transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/Untitled design (5).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget_17 = QtWidgets.QWidget(self.widget)
        self.widget_17.setGeometry(QtCore.QRect(20, 10, 1161, 793))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        self.widget_17.setFont(font)
        self.widget_17.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 80));\n"
"border-radius:15px;")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_2.setContentsMargins(12, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_18 = QtWidgets.QWidget(self.widget_17)
        self.widget_18.setMinimumSize(QtCore.QSize(180, 0))
        self.widget_18.setStyleSheet("background-color:#ECE1C5;")
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_19 = QtWidgets.QWidget(self.widget_18)
        self.widget_19.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_19.setStyleSheet("background-color:transparent;")
        self.widget_19.setObjectName("widget_19")
        self.Dashboard_button = QtWidgets.QToolButton(self.widget_19)
        self.Dashboard_button.setGeometry(QtCore.QRect(-1, 10, 161, 111))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Dashboard_button.setFont(font)
        self.Dashboard_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dashboard_button.setStyleSheet("QToolButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 15px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"background-color: rgba(244,237,228,200);\n"
"border-radius: 20px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-dashboard-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-dashboard-80.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.Dashboard_button.setIcon(icon)
        self.Dashboard_button.setIconSize(QtCore.QSize(100, 100))
        self.Dashboard_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Dashboard_button.setObjectName("Dashboard_button")
        self.verticalLayout_5.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setStyleSheet("background-color:transparent;")
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_21 = QtWidgets.QWidget(self.widget_20)
        self.widget_21.setObjectName("widget_21")
        self.Inventory = QtWidgets.QPushButton(self.widget_21)
        self.Inventory.setGeometry(QtCore.QRect(-19, 14, 181, 51))
        font = QtGui.QFont()
        self.Inventory.setFont(font)
        self.Inventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Inventory.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Inventory.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"  
"    border: none;\n"
"    text-align: center;\n"
"    width: 200px; /* Default width */\n"
"    height: 50px; /* Optional height for consistency */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(244,237,228,200);\n"
"border-radius: 20px;\n"
"    width: 300px; /* Width change on hover */\n"
" \n"
"}\n"
"")
        self.Inventory.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/inventory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/inventory.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/inventory.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/inventory-w.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/inventory-w.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/inventory-w.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/inventory-w.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.Inventory.setIcon(icon1)
        self.Inventory.setIconSize(QtCore.QSize(50, 50))
        self.Inventory.setObjectName("Inventory")
        self.verticalLayout_6.addWidget(self.widget_21)
        self.widget_22 = QtWidgets.QWidget(self.widget_20)
        self.widget_22.setObjectName("widget_22")
        self.Order = QtWidgets.QPushButton(self.widget_22)
        self.Order.setGeometry(QtCore.QRect(-20, 20, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Order.setFont(font)
        self.Order.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Order.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Order.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    text-align: center;\n"
"    width: 200px; /* Default width */\n"
"    height: 50px; /* Optional height for consistency */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(244,237,228,200);\n"
"border-radius: 20px;\n"
"    width: 300px; /* Width change on hover */\n"
"}\n"
"")
        self.Order.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-order-management-64 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-order-management-64 (1) 1.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.Order.setIcon(icon2)
        self.Order.setIconSize(QtCore.QSize(50, 50))
        self.Order.setObjectName("Order")
        self.verticalLayout_6.addWidget(self.widget_22)
        self.widget_23 = QtWidgets.QWidget(self.widget_20)
        self.widget_23.setObjectName("widget_23")
        self.Report = QtWidgets.QPushButton(self.widget_23)
        self.Report.setGeometry(QtCore.QRect(-20, 20, 181, 55))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Report.setFont(font)
        self.Report.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Report.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Report.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    text-align: center;\n"
"    width: 200px; /* Default width */\n"
"    height: 50px; /* Optional height for consistency */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(244,237,228,200);\n"
"border-radius: 20px;\n"
"    width: 300px; /* Width change on hover */\n"
"}\n"
"")
        self.Report.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-health-graph-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-health-graph-50 (1).png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.Report.setIcon(icon3)
        self.Report.setIconSize(QtCore.QSize(50, 50))
        self.Report.setObjectName("Report")
        self.verticalLayout_6.addWidget(self.widget_23)
        self.widget_24 = QtWidgets.QWidget(self.widget_20)
        self.widget_24.setObjectName("widget_24")
        self.Supplier = QtWidgets.QPushButton(self.widget_24)
        self.Supplier.setGeometry(QtCore.QRect(-20, 20, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Supplier.setFont(font)
        self.Supplier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Supplier.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Supplier.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    text-align: center;\n"
"    width: 200px; /* Default width */\n"
"    height: 50px; /* Optional height for consistency */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(244,237,228,200);\n"
"border-radius: 20px;\n"
"    width: 300px; /* Width change on hover */\n"
"}\n"
"")
        self.Supplier.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/supplier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-supplier-50.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.Supplier.setIcon(icon4)
        self.Supplier.setIconSize(QtCore.QSize(50, 50))
        self.Supplier.setObjectName("Supplier")
        self.verticalLayout_6.addWidget(self.widget_24)
        self.widget_25 = QtWidgets.QWidget(self.widget_20)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_6.addWidget(self.widget_25)
        self.widget_26 = QtWidgets.QWidget(self.widget_20)
        self.widget_26.setObjectName("widget_26")
        self.Logout = QtWidgets.QPushButton(self.widget_26)
        self.Logout.setGeometry(QtCore.QRect(30, 20, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Logout.setFont(font)
        self.Logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Logout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Logout.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"border:null;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(244,237,228,200);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"")
        self.Logout.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/w-logot.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.Logout.setIcon(icon5)
        self.Logout.setIconSize(QtCore.QSize(40, 40))
        self.Logout.setObjectName("Logout")
        self.verticalLayout_6.addWidget(self.widget_26)
        self.verticalLayout_5.addWidget(self.widget_20)
        self.horizontalLayout_2.addWidget(self.widget_18)
        self.widget_27 = QtWidgets.QWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_27.sizePolicy().hasHeightForWidth())
        self.widget_27.setSizePolicy(sizePolicy)
        self.widget_27.setStyleSheet("background-color:transparent;")
        self.widget_27.setObjectName("widget_27")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_27)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_29 = QtWidgets.QWidget(self.widget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_29.sizePolicy().hasHeightForWidth())
        self.widget_29.setSizePolicy(sizePolicy)
        self.widget_29.setMinimumSize(QtCore.QSize(0, 55))
        self.widget_29.setStyleSheet("background-color:transparent;")
        self.widget_29.setObjectName("widget_29")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_29)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 901, 701))
        self.stackedWidget.setStyleSheet(" background-color: transparent;\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.InventoryPage = QtWidgets.QWidget()
        self.InventoryPage.setObjectName("InventoryPage")
        self.InventoryTable = QtWidgets.QTableWidget(self.InventoryPage)
        self.InventoryTable.setGeometry(QtCore.QRect(60, 140, 790, 450))
        self.InventoryTable.setStyleSheet("QTableWidget {\n"
"    border: 3px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: #ECE1C5;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #C5B08A;\n"
"}")
        self.InventoryTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.InventoryTable.setTabKeyNavigation(False)
        self.InventoryTable.setProperty("showDropIndicator", False)
        self.InventoryTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.InventoryTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.InventoryTable.setObjectName("InventoryTable")
        self.InventoryTable.setColumnCount(6)
        self.InventoryTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.InventoryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.InventoryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.InventoryTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.InventoryTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.InventoryTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.InventoryTable.setHorizontalHeaderItem(5, item)
        self.InventoryTable.horizontalHeader().setDefaultSectionSize(131)
        self.InventoryTable.verticalHeader().setVisible(False)
        self.InventoryTable.verticalHeader().setHighlightSections(False)
        self.inventory_label = QtWidgets.QLabel(self.InventoryPage)
        self.inventory_label.setGeometry(QtCore.QRect(80, 20, 451, 41))
        self.inventory_label.setStyleSheet("background-color: transparent;\n"
"font-size: 32px;\n"
"color: #FFFFFF;\n"
"font: \"Inter\";\n"
"font-weight: bold;\n"
"")
        self.inventory_label.setAlignment(QtCore.Qt.AlignCenter)
        self.inventory_label.setObjectName("inventory_label")
        self.inicon_label = QtWidgets.QLabel(self.InventoryPage)
        self.inicon_label.setGeometry(QtCore.QRect(30, 10, 50, 56))
        self.inicon_label.setText("")
        self.inicon_label.setPixmap(QtGui.QPixmap(":/newPrefix/inventory-w.png"))
        self.inicon_label.setScaledContents(False)
        self.inicon_label.setObjectName("inicon_label")
        self.Search = QtWidgets.QLineEdit(self.InventoryPage)
        self.Search.setGeometry(QtCore.QRect(630, 70, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.Search.setFont(font)
        self.Search.setStyleSheet("background-color:#ECE1C5;\n"
"border-radius:10px;")
        self.Search.setText("")
        self.Search.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.Search.setDragEnabled(True)
        self.Search.setReadOnly(False)
        self.Search.setClearButtonEnabled(False)
        self.Search.setObjectName("Search")
        self.searchicon_lable = QtWidgets.QLabel(self.InventoryPage)
        self.searchicon_lable.setGeometry(QtCore.QRect(820, 70, 30, 30))
        self.searchicon_lable.setText("")
        self.searchicon_lable.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-search-24.png"))
        self.searchicon_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.searchicon_lable.setObjectName("searchicon_lable")
        self.Add = QtWidgets.QPushButton(self.InventoryPage)
        self.Add.setGeometry(QtCore.QRect(180, 660, 150, 41))
        self.Add.setStyleSheet("\n"
"QPushButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 20px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"border:null;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#6A5F4B;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/plus-solid 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Add.setIcon(icon6)
        self.Add.setObjectName("Add")
        self.Edit = QtWidgets.QPushButton(self.InventoryPage)
        self.Edit.setGeometry(QtCore.QRect(400, 660, 150, 41))
        self.Edit.setStyleSheet("\n"
"QPushButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 20px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"border:null;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#6A5F4B;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/pen-to-square-solid 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Edit.setIcon(icon7)
        self.Edit.setObjectName("Edit")
        self.Delete = QtWidgets.QPushButton(self.InventoryPage)
        self.Delete.setGeometry(QtCore.QRect(620, 660, 150, 41))
        self.Delete.setStyleSheet("\n"
"QPushButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 20px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"border:null;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#6A5F4B;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/trash-can-solid 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Delete.setIcon(icon8)
        self.Delete.setObjectName("Delete")
        self.stackedWidget.addWidget(self.InventoryPage)
        self.OrderPage = QtWidgets.QWidget()
        self.OrderPage.setObjectName("OrderPage")
        self.ordericon_label = QtWidgets.QLabel(self.OrderPage)
        self.ordericon_label.setGeometry(QtCore.QRect(30, 10, 50, 56))
        self.ordericon_label.setText("")
        self.ordericon_label.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-order-management-64 (1) 1.png"))
        self.ordericon_label.setScaledContents(False)
        self.ordericon_label.setObjectName("ordericon_label")
        self.order_label = QtWidgets.QLabel(self.OrderPage)
        self.order_label.setGeometry(QtCore.QRect(80, 20, 371, 41))
        self.order_label.setStyleSheet("background-color: transparent;\n"
"font-size: 32px;\n"
"color: #FFFFFF;\n"
"font: \"Inter\";\n"
"font-weight: bold;\n"
"")
        self.order_label.setAlignment(QtCore.Qt.AlignCenter)
        self.order_label.setObjectName("order_label")
        self.Search2 = QtWidgets.QLineEdit(self.OrderPage)
        self.Search2.setGeometry(QtCore.QRect(630, 70, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.Search2.setFont(font)
        self.Search2.setStyleSheet("background-color:#ECE1C5;\n"
"border-radius:10px;")
        self.Search2.setText("")
        self.Search2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.Search2.setDragEnabled(True)
        self.Search2.setReadOnly(False)
        self.Search2.setClearButtonEnabled(False)
        self.Search2.setObjectName("Search2")
        self.searchicon_label = QtWidgets.QLabel(self.OrderPage)
        self.searchicon_label.setGeometry(QtCore.QRect(820, 70, 30, 30))
        self.searchicon_label.setText("")
        self.searchicon_label.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-search-24.png"))
        self.searchicon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.searchicon_label.setObjectName("searchicon_label")
        self.Add_4 = QtWidgets.QPushButton(self.OrderPage)
        self.Add_4.setGeometry(QtCore.QRect(180, 660, 150, 41))
        self.Add_4.setStyleSheet("\n"
"QPushButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 20px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"border:null;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#6A5F4B;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"")
        self.Add_4.setIcon(icon6)
        self.Add_4.setObjectName("Add_4")
        self.Edit_2 = QtWidgets.QPushButton(self.OrderPage)
        self.Edit_2.setGeometry(QtCore.QRect(400, 660, 150, 41))
        self.Edit_2.setStyleSheet("\n"
"QPushButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 20px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"border:null;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#6A5F4B;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"")
        self.Edit_2.setIcon(icon7)
        self.Edit_2.setObjectName("Edit_2")
        self.Delete_2 = QtWidgets.QPushButton(self.OrderPage)
        self.Delete_2.setGeometry(QtCore.QRect(620, 660, 150, 41))
        self.Delete_2.setStyleSheet("\n"
"QPushButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 20px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"border:null;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#6A5F4B;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"")
        self.Delete_2.setIcon(icon8)
        self.Delete_2.setObjectName("Delete_2")
        self.OrderTable = QtWidgets.QTableWidget(self.OrderPage)
        self.OrderTable.setGeometry(QtCore.QRect(60, 140, 811, 450))
        self.OrderTable.setStyleSheet("QTableWidget {\n"
"    border: 3px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: #ECE1C5;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #C5B08A;\n"
"}")
        self.OrderTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.OrderTable.setTabKeyNavigation(False)
        self.OrderTable.setProperty("showDropIndicator", False)
        self.OrderTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.OrderTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.OrderTable.setObjectName("OrderTable")
        self.OrderTable.setColumnCount(7)
        self.OrderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(6, item)
        self.OrderTable.horizontalHeader().setDefaultSectionSize(130)
        self.OrderTable.verticalHeader().setVisible(False)
        self.OrderTable.verticalHeader().setHighlightSections(False)
        self.stackedWidget.addWidget(self.OrderPage)
        self.SalesReportPage = QtWidgets.QWidget()
        self.SalesReportPage.setObjectName("SalesReportPage")
        self.SalesReportTable = QtWidgets.QTableWidget(self.SalesReportPage)
        self.SalesReportTable.setGeometry(QtCore.QRect(60, 140, 791, 450))
        self.SalesReportTable.setStyleSheet("QTableWidget {\n"
"    border: 3px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: #ECE1C5;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #C5B08A;\n"
"}")
        self.SalesReportTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.SalesReportTable.setTabKeyNavigation(False)
        self.SalesReportTable.setProperty("showDropIndicator", False)
        self.SalesReportTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.SalesReportTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.SalesReportTable.setObjectName("SalesReportTable")
        self.SalesReportTable.setColumnCount(7)
        self.SalesReportTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.SalesReportTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SalesReportTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SalesReportTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SalesReportTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SalesReportTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SalesReportTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.SalesReportTable.setHorizontalHeaderItem(6, item)
        self.SalesReportTable.horizontalHeader().setDefaultSectionSize(130)
        self.SalesReportTable.verticalHeader().setVisible(False)
        self.SalesReportTable.verticalHeader().setHighlightSections(False)
        self.purchaseicon_label = QtWidgets.QLabel(self.SalesReportPage)
        self.purchaseicon_label.setGeometry(QtCore.QRect(30, 10, 50, 56))
        self.purchaseicon_label.setText("")
        self.purchaseicon_label.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-graph-report-50.png"))
        self.purchaseicon_label.setScaledContents(False)
        self.purchaseicon_label.setObjectName("purchaseicon_label")
        self.purchase_label = QtWidgets.QLabel(self.SalesReportPage)
        self.purchase_label.setGeometry(QtCore.QRect(80, 20, 371, 41))
        self.purchase_label.setStyleSheet("background-color: transparent;\n"
"font-size: 32px;\n"
"color: #FFFFFF;\n"
"font: \"Inter\";\n"
"font-weight: bold;\n"
"")
        self.purchase_label.setAlignment(QtCore.Qt.AlignCenter)
        self.purchase_label.setObjectName("purchase_label")
        self.Search3 = QtWidgets.QLineEdit(self.SalesReportPage)
        self.Search3.setGeometry(QtCore.QRect(630, 70, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.Search3.setFont(font)
        self.Search3.setStyleSheet("background-color:#ECE1C5;\n"
"border-radius:10px;")
        self.Search3.setText("")
        self.Search3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.Search3.setDragEnabled(True)
        self.Search3.setReadOnly(False)
        self.Search3.setClearButtonEnabled(False)
        self.Search3.setObjectName("Search3")
        self.searchicon_label_2 = QtWidgets.QLabel(self.SalesReportPage)
        self.searchicon_label_2.setGeometry(QtCore.QRect(820, 70, 30, 30))
        self.searchicon_label_2.setText("")
        self.searchicon_label_2.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-search-24.png"))
        self.searchicon_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.searchicon_label_2.setObjectName("searchicon_label_2")
        self.stackedWidget.addWidget(self.SalesReportPage)
        self.SupplierManagementPage = QtWidgets.QWidget()
        self.SupplierManagementPage.setObjectName("SupplierManagementPage")
        self.supicon_label = QtWidgets.QLabel(self.SupplierManagementPage)
        self.supicon_label.setGeometry(QtCore.QRect(30, 10, 50, 56))
        self.supicon_label.setText("")
        self.supicon_label.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-supplier-50.png"))
        self.supicon_label.setScaledContents(False)
        self.supicon_label.setObjectName("supicon_label")
        self.supplier_label = QtWidgets.QLabel(self.SupplierManagementPage)
        self.supplier_label.setGeometry(QtCore.QRect(80, 20, 371, 41))
        self.supplier_label.setStyleSheet("background-color: transparent;\n"
"font-size: 32px;\n"
"color: #FFFFFF;\n"
"font: \"Inter\";\n"
"font-weight: bold;\n"
"")
        self.supplier_label.setAlignment(QtCore.Qt.AlignCenter)
        self.supplier_label.setObjectName("supplier_label")
        self.SupplierManagementTable = QtWidgets.QTableWidget(self.SupplierManagementPage)
        self.SupplierManagementTable.setGeometry(QtCore.QRect(140, 140, 660, 450))
        self.SupplierManagementTable.setStyleSheet("QTableWidget {\n"
"    border: 3px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: #ECE1C5;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #C5B08A;\n"
"}")
        self.SupplierManagementTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.SupplierManagementTable.setTabKeyNavigation(False)
        self.SupplierManagementTable.setProperty("showDropIndicator", False)
        self.SupplierManagementTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.SupplierManagementTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.SupplierManagementTable.setObjectName("SupplierManagementTable")
        self.SupplierManagementTable.setColumnCount(4)
        self.SupplierManagementTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.SupplierManagementTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SupplierManagementTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SupplierManagementTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SupplierManagementTable.setHorizontalHeaderItem(3, item)
        self.SupplierManagementTable.horizontalHeader().setDefaultSectionSize(165)
        self.SupplierManagementTable.verticalHeader().setVisible(False)
        self.SupplierManagementTable.verticalHeader().setHighlightSections(False)
        self.supplier_search = QtWidgets.QLineEdit(self.SupplierManagementPage)
        self.supplier_search.setGeometry(QtCore.QRect(630, 70, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.supplier_search.setFont(font)
        self.supplier_search.setStyleSheet("background-color:#ECE1C5;\n"
"border-radius:10px;")
        self.supplier_search.setText("")
        self.supplier_search.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.supplier_search.setDragEnabled(True)
        self.supplier_search.setReadOnly(False)
        self.supplier_search.setClearButtonEnabled(False)
        self.supplier_search.setObjectName("Search4")
        self.searchicon_label_3 = QtWidgets.QLabel(self.SupplierManagementPage)
        self.searchicon_label_3.setGeometry(QtCore.QRect(820, 70, 30, 30))
        self.searchicon_label_3.setText("")
        self.searchicon_label_3.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-search-24.png"))
        self.searchicon_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.searchicon_label_3.setObjectName("searchicon_label_3")
        self.Edit_5 = QtWidgets.QPushButton(self.SupplierManagementPage)
        self.Edit_5.setGeometry(QtCore.QRect(370, 660, 150, 41))
        self.Edit_5.setStyleSheet("\n"
"QPushButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 20px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"border:null;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#6A5F4B;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"")
        self.Edit_5.setIcon(icon7)
        self.Edit_5.setObjectName("Edit_5")
        self.Delete_5 = QtWidgets.QPushButton(self.SupplierManagementPage)
        self.Delete_5.setGeometry(QtCore.QRect(590, 660, 150, 41))
        self.Delete_5.setStyleSheet("\n"
"QPushButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 20px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"border:null;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#6A5F4B;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"")
        self.Delete_5.setIcon(icon8)
        self.Delete_5.setObjectName("Delete_5")
        self.Add_7 = QtWidgets.QPushButton(self.SupplierManagementPage)
        self.Add_7.setGeometry(QtCore.QRect(160, 660, 150, 41))
        self.Add_7.setStyleSheet("\n"
"QPushButton{\n"
"background-color:#ECE1C5;\n"
"border-radius:20px;\n"
"font-size: 20px;\n"
"color: black;\n"
"font: \"Jost\" ;\n"
"font-weight: bold;\n"
"border:null;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#6A5F4B;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"")
        self.Add_7.setIcon(icon6)
        self.Add_7.setObjectName("Add_7")
        self.stackedWidget.addWidget(self.SupplierManagementPage)
        self.label_3 = QtWidgets.QLabel(self.widget_29)
        self.label_3.setGeometry(QtCore.QRect(130, 0, 700, 700))
        self.label_3.setStyleSheet("background-color:transparent")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/logo1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.stackedWidget.raise_()
        self.verticalLayout_8.addWidget(self.widget_29)
        self.horizontalLayout_2.addWidget(self.widget_27)
        Sugarcafe.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Sugarcafe)
        self.statusbar.setObjectName("statusbar")
        Sugarcafe.setStatusBar(self.statusbar)

        self.retranslateUi(Sugarcafe)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Sugarcafe)

    def retranslateUi(self, Sugarcafe):
        _translate = QtCore.QCoreApplication.translate
        Sugarcafe.setWindowTitle(_translate("Sugarcafe", "MainWindow"))
        self.Dashboard_button.setText(_translate("Sugarcafe", "Dashboard"))
        item = self.InventoryTable.horizontalHeaderItem(0)
        item.setText(_translate("Sugarcafe", "Product ID"))
        item = self.InventoryTable.horizontalHeaderItem(1)
        item.setText(_translate("Sugarcafe", "Product"))
        item = self.InventoryTable.horizontalHeaderItem(2)
        item.setText(_translate("Sugarcafe", "Quantity On Hand"))
        item = self.InventoryTable.horizontalHeaderItem(3)
        item.setText(_translate("Sugarcafe", "Unit Price"))
        item = self.InventoryTable.horizontalHeaderItem(4)
        item.setText(_translate("Sugarcafe", "Description"))
        item = self.InventoryTable.horizontalHeaderItem(5)
        item.setText(_translate("Sugarcafe", "Supplier ID"))
        self.inventory_label.setText(_translate("Sugarcafe", "INVENTORY MANAGEMENT"))
        self.Search.setPlaceholderText(_translate("Sugarcafe", "Search"))
        self.Add.setText(_translate("Sugarcafe", "ADD"))
        self.Edit.setText(_translate("Sugarcafe", "EDIT"))
        self.Delete.setText(_translate("Sugarcafe", "DELETE"))
        self.order_label.setText(_translate("Sugarcafe", "ORDER MANAGEMENT"))
        self.Search2.setPlaceholderText(_translate("Sugarcafe", "Search"))
        self.Add_4.setText(_translate("Sugarcafe", "ADD"))
        self.Edit_2.setText(_translate("Sugarcafe", "EDIT"))
        self.Delete_2.setText(_translate("Sugarcafe", "DELETE"))
        item = self.OrderTable.horizontalHeaderItem(0)
        item.setText(_translate("Sugarcafe", "Date"))
        item = self.OrderTable.horizontalHeaderItem(1)
        item.setText(_translate("Sugarcafe", "Order ID"))
        item = self.OrderTable.horizontalHeaderItem(2)
        item.setText(_translate("Sugarcafe", "Product"))
        item = self.OrderTable.horizontalHeaderItem(3)
        item.setText(_translate("Sugarcafe", "Quantity"))
        item = self.OrderTable.horizontalHeaderItem(4)
        item.setText(_translate("Sugarcafe", "Price"))
        item = self.OrderTable.horizontalHeaderItem(5)
        item.setText(_translate("Sugarcafe", "Total Cost"))
        item = self.OrderTable.horizontalHeaderItem(6)
        item.setText(_translate("Sugarcafe", "Payment Method"))
        item = self.SalesReportTable.horizontalHeaderItem(0)
        item.setText(_translate("Sugarcafe", "Sales Report No."))
        item = self.SalesReportTable.horizontalHeaderItem(1)
        item.setText(_translate("Sugarcafe", "Date"))
        item = self.SalesReportTable.horizontalHeaderItem(2)
        item.setText(_translate("Sugarcafe", "Order ID"))
        item = self.SalesReportTable.horizontalHeaderItem(3)
        item.setText(_translate("Sugarcafe", "Product "))
        item = self.SalesReportTable.horizontalHeaderItem(4)
        item.setText(_translate("Sugarcafe", "Supplier Name"))
        item = self.SalesReportTable.horizontalHeaderItem(5)
        item.setText(_translate("Sugarcafe", "Total Sales"))
        item = self.SalesReportTable.horizontalHeaderItem(6)
        item.setText(_translate("Sugarcafe", "Payment Method"))
        self.purchase_label.setText(_translate("Sugarcafe", "Check Purchase Report"))
        self.Search3.setPlaceholderText(_translate("Sugarcafe", "Search"))
        self.supplier_label.setText(_translate("Sugarcafe", "Supplier\'s Information"))
        item = self.SupplierManagementTable.horizontalHeaderItem(0)
        item.setText(_translate("Sugarcafe", "Supplier ID"))
        item = self.SupplierManagementTable.horizontalHeaderItem(1)
        item.setText(_translate("Sugarcafe", "Supplier Name"))
        item = self.SupplierManagementTable.horizontalHeaderItem(2)
        item.setText(_translate("Sugarcafe", "Email Address"))
        item = self.SupplierManagementTable.horizontalHeaderItem(3)
        item.setText(_translate("Sugarcafe", "Contact Info."))
        self.Search.setPlaceholderText(_translate("Sugarcafe", "Search"))
        self.Edit_5.setText(_translate("Sugarcafe", "EDIT"))
        self.Delete_5.setText(_translate("Sugarcafe", "DELETE"))
        self.Add_7.setText(_translate("Sugarcafe", "ADD"))
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sugarcafe = QtWidgets.QMainWindow()
    ui = Ui_Sugarcafe()
    ui.setupUi(Sugarcafe)
    Sugarcafe.show()
    sys.exit(app.exec_())